// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace GamePal
{
	public partial class HomeController : UITabBarController
	{
		public HomeController (IntPtr handle) : base (handle)
		{
		}
	}
}
